### ISSUE TITLE
produce top-k answers?

### ISSUE THREAD

**Issue by yuchenlin** [shmsw25/bart-closed-book-qa#6]
Hi Sewon,

Thank you very much for this great repo. I was wondering how we can easily get the top-k best answer predictions (in the inference time) after training. Do you have any pointers? Thank you very much!

**Comment by shmsw25** [comment]
Hi @yuchenlin, thanks for your interest. There's no easy way to do it with this codebase, unfortunately. However, you will be able to implement such a function by creating a `generate` method in the model class that override the original generate method (which is used in [this line](https://github.com/shmsw25/bart-closed-book-qa/blob/master/run.py#L133)). 

One concrete suggestion is, when you are using the beam search, the transformers will use a class `BeamScorer` to keep the best k outputs, and then call `finalize` ([here](https://github.com/huggingface/transformers/blob/9edafaebef543478fbf50dcbbffe79fadcfdb5da/src/transformers/generation_beam_search.py#L261)) in order to select the top 1 output. You may try modifying this so that it returns all top k outputs.

Nonetheless, it is possible that all of those top-k best answers will look very similar, due to the property of sequence-to-sequence approach. How to get a more diverse set of top-k predictions seems to be an open question.

**Comment by yuchenlin** [comment]
Hi Sewon,

Thank you for your help and suggestion! Yeah, I actually modified the fairseq code to get it to work now (but based on an outdated version of fariseq and in my own project). I can follow your suggestion to create a PR here later if you like that feature as well.  :)

**Comment by shmsw25** [comment]
That sounds good, thanks!
